name: Test our Secret Value

on:
  workflow_dispatch: # Trigger the workflow manually

env:
  ## Sets environment variable
  MEANING_OF_LIFE: ${{secrets.MEANING_OF_LIFE}}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i
      - name: Run test script
        run: npm run test
